name: sagem
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  rive: ^0.12.3
  flutter_svg:
  flutter_spinkit: ^5.2.1
  qr_bar_code_scanner_dialog: ^0.0.5
  flutter_secure_storage: ^9.0.0
  flutter:
    sdk: flutter
  http: ^0.13.5
  get: ^4.6.6
  # flutter_form_bloc: ^1.0.0
  # form_builder_validators: ^9.1.0
  intl:
  flutter_form_bloc: ^0.31.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  firebase_core:
  awesome_notifications: ^0.8.2
  flutter_background_service: ^5.0.5
  firebase_messaging:
  awesome_snackbar_content: ^0.1.1
  filter_list: ^1.0.2
  multiselect_dropdown_flutter: ^0.0.7
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  image_path: assets/Backgrounds/android/play_store_512.png
  adaptive_icon_background: #ffffff
  adaptive_icon_foreground: assets/Backgrounds/android/icons.png

flutter:
  uses-material-design: true
  assets:
    - assets/avaters/
    - assets/Backgrounds/
    - assets/icons/
    - assets/RiveAssets/
  fonts:
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700
